import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const hospitals = [
  {
    nameAr: 'مستشفى دار الفؤاد - 6 أكتوبر',
    nameEn: 'Dar Al Fouad Hospital - 6th of October',
    slug: 'dar-al-fouad-october',
    typeSlug: 'private',
    address: 'محور 26 يوليو، المنطقة السياحية، 6 أكتوبر، الجيزة',
    phone: '16370',
    website: 'https://daralfouad.org',
    hasEmergency: true,
    isFeatured: true,
    lat: 30.0074,
    lng: 30.9756,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
    logo: 'https://ui-avatars.com/api/?name=Dar+Al+Fouad&background=0D8ABC&color=fff',
    description: 'واحدة من أكبر المستشفيات الخاصة في مصر، معتمدة من JCI.',
  },
  {
    nameAr: 'مستشفى السلام الدولي - المعادي',
    nameEn: 'As-Salam International Hospital - Maadi',
    slug: 'as-salam-maadi',
    typeSlug: 'private',
    address: 'كورنيش النيل، المعادي، القاهرة',
    phone: '19885',
    website: 'https://assalamhospital.com',
    hasEmergency: true,
    isFeatured: true,
    lat: 29.9833,
    lng: 31.2333,
    logo: 'https://ui-avatars.com/api/?name=As+Salam&background=0D8ABC&color=fff',
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
    description: 'مستشفى متعدد التخصصات يقدم رعاية صحية عالمية المستوى.',
  },
  {
    nameAr: 'مستشفى كليوباترا - مصر الجديدة',
    nameEn: 'Cleopatra Hospital - Heliopolis',
    slug: 'cleopatra-heliopolis',
    typeSlug: 'private',
    address: '39 شارع كليوباترا، ميدان صلاح الدين، مصر الجديدة، القاهرة',
    phone: '19662',
    website: 'https://www.cleopatrahospitals.com',
    hasEmergency: true,
    isFeatured: true,
    lat: 30.0898,
    lng: 31.3287,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'المستشفى الجوي التخصصي',
    nameEn: 'Air Force Specialized Hospital',
    slug: 'air-force-specialized',
    typeSlug: 'military',
    address: 'شارع التسعين، التجمع الخامس، القاهرة الجديدة',
    phone: '19448',
    hasEmergency: true,
    isFeatured: true,
    lat: 30.0264,
    lng: 31.4542,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مستشفى 57357 لسرطان الأطفال',
    nameEn: 'Children\'s Cancer Hospital 57357',
    slug: '57357-hospital',
    typeSlug: 'charity',
    address: '1 شارع سكة الإمام، السيدة زينب، القاهرة',
    phone: '19057',
    website: 'https://www.57357.org',
    hasEmergency: true,
    isFeatured: true,
    lat: 30.0234,
    lng: 31.2356,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مستشفى السعودي الألماني - القاهرة',
    nameEn: 'Saudi German Hospital - Cairo',
    slug: 'saudi-german-cairo',
    typeSlug: 'private',
    address: 'طريق جوزيف تيتو، النزهة، مصر الجديدة، القاهرة',
    phone: '16259',
    website: 'https://sghcairo.com',
    hasEmergency: true,
    isFeatured: true,
    lat: 30.1333,
    lng: 31.3833,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مستشفى القصر العيني',
    nameEn: 'Kasr Al Ainy Hospital',
    slug: 'kasr-al-ainy',
    typeSlug: 'university',
    address: 'شارع القصر العيني، القاهرة',
    phone: '0223646394',
    hasEmergency: true,
    isFeatured: false,
    lat: 30.0333,
    lng: 31.2333,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مستشفى الأندلسية - المعادي',
    nameEn: 'Andalusia Hospital - Maadi',
    slug: 'andalusia-maadi',
    typeSlug: 'private',
    address: 'شارع النصر، المعادي الجديدة، القاهرة',
    phone: '16781',
    hasEmergency: true,
    isFeatured: true,
    lat: 29.9750,
    lng: 31.2850,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مستشفى النيل بدراوي',
    nameEn: 'Nile Badrawi Hospital',
    slug: 'nile-badrawi',
    typeSlug: 'private',
    address: 'كورنيش النيل، المعادي، القاهرة',
    phone: '0225240022',
    hasEmergency: true,
    isFeatured: false,
    lat: 29.9667,
    lng: 31.2500,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مستشفى الشرطة - العجوزة',
    nameEn: 'Police Hospital - Agouza',
    slug: 'police-agouza',
    typeSlug: 'military',
    address: 'شارع النيل، العجوزة، الجيزة',
    phone: '0233044444',
    hasEmergency: true,
    isFeatured: false,
    lat: 30.0500,
    lng: 31.2167,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مستشفى بهية للكشف المبكر عن سرطان الثدي',
    nameEn: 'Baheya Hospital',
    slug: 'baheya',
    typeSlug: 'charity',
    address: 'شارع الهرم، الجيزة',
    phone: '16602',
    website: 'https://baheya.org',
    hasEmergency: false,
    isFeatured: true,
    lat: 29.9950,
    lng: 31.1550,
    workingHours: JSON.stringify({
      sunday: { open: '09:00', close: '17:00' },
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: 'Closed', close: 'Closed' },
      saturday: { open: '09:00', close: '17:00' },
    }),
  },
  {
    nameAr: 'مستشفى المقاولون العرب',
    nameEn: 'Arab Contractors Hospital',
    slug: 'arab-contractors',
    typeSlug: 'private',
    address: 'طريق النصر، الجبل الأخضر، مدينة نصر، القاهرة',
    phone: '0223426000',
    hasEmergency: true,
    isFeatured: false,
    lat: 30.0500,
    lng: 31.2833,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مستشفى معهد ناصر',
    nameEn: 'Nasser Institute Hospital',
    slug: 'nasser-institute',
    typeSlug: 'specialized',
    address: 'كورنيش النيل، شبرا، القاهرة',
    phone: '0222039164',
    hasEmergency: true,
    isFeatured: true,
    lat: 30.0833,
    lng: 31.2333,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مركز د. مجدي يعقوب للقلب',
    nameEn: 'Magdi Yacoub Heart Foundation',
    slug: 'magdi-yacoub-aswan',
    typeSlug: 'charity',
    address: 'أسوان، مصر',
    phone: '19731',
    website: 'https://myf-egypt.org',
    hasEmergency: true,
    isFeatured: true,
    lat: 24.0889,
    lng: 32.8997,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  },
  {
    nameAr: 'مستشفى الشروق',
    nameEn: 'El Sherouk Hospital',
    slug: 'el-sherouk-mohandessin',
    typeSlug: 'private',
    address: 'شارع بحر الغزال، المهندسين، الجيزة',
    phone: '0233044444',
    hasEmergency: true,
    isFeatured: false,
    lat: 30.0550,
    lng: 31.2000,
    workingHours: JSON.stringify({
      sunday: { open: '00:00', close: '23:59' },
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
    }),
  }
];

async function seed() {
  console.log('Seeding real hospitals...');

  for (const h of hospitals) {
    const type = await prisma.hospitalType.findUnique({ where: { slug: h.typeSlug } });
    if (!type) {
      console.error(`Type not found: ${h.typeSlug}`);
      continue;
    }

    await prisma.hospital.upsert({
      where: { slug: h.slug },
      update: {
        nameAr: h.nameAr,
        nameEn: h.nameEn,
        address: h.address,
        phone: h.phone,
        website: h.website,
        hasEmergency: h.hasEmergency,
        isFeatured: h.isFeatured,
        lat: h.lat,
        lng: h.lng,
        workingHours: h.workingHours,
        description: h.description,
        typeId: type.id,
      },
      create: {
        nameAr: h.nameAr,
        nameEn: h.nameEn,
        slug: h.slug,
        address: h.address,
        phone: h.phone,
        website: h.website,
        hasEmergency: h.hasEmergency,
        isFeatured: h.isFeatured,
        lat: h.lat,
        lng: h.lng,
        workingHours: h.workingHours,
        description: h.description,
        typeId: type.id,
      },
    });
    console.log(`Seeded: ${h.nameEn}`);
  }
  
  console.log('Real hospitals seeded successfully.');
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
